---
# Install keepalived on coreos hosts

  # ---------------------------------------------- Requirements.
  - name: Fail if peer_ip is not defined
    fail: msg="This role requires 'peer_ip' as a variable"
    when: peer_ip is not defined

  - name: Fail if keepalived_priority is not defined
    fail: msg="This role requires 'keepalived_priority' as a variable"
    when: keepalived_priority is not defined

  - name: Fail if floating_ip is not defined
    fail: msg="This role requires 'floating_ip' as a variable"
    when: floating_ip is not defined

  # ---------------------------------------------- Debug
  # - debug: "msg={{ peer_ip }}"
  # - debug: "msg={{ keepalived_priority }}"
  # - debug: "msg={{ floating_ip }}"
  # - debug: "msg={{ ansible_ssh_host }}"

  # ---------------------------------------------- Core logic.

  - name: Ensure /opt/keepalived exists
    file: path=/opt/keepalived/ state=directory

  - name: Copy binary keepalived
    copy: src=keepalived dest=/opt/keepalived/keepalived mode=755

  - name: Copy binary genhash
    copy: src=genhash dest=/opt/keepalived/genhash mode=755

  - name: Template keepalived.conf
    template: src=keepalived.conf.j2 dest=/opt/keepalived/keepalived.conf
