
- name: Fail if boxnumber is not defined
  fail: msg="This task requires 'boxnumber' variable"
  when: boxnumber is not defined

- name: Set vm_name if need be
  set_fact:
      vm_name: "coreos{{ boxnumber }}"
  when: vm_name is not defined

- name: Undefine namespace
  virt: "name={{ vm_name }} command=undefine"