---
# A set of actions for spinning up coreos boxes with libvirt.
# Requires a series of variables, defined at the beginning of tasks here.
# Otherwise takes these modes:
# mode == "create"     --> create a box with boxnumber
# mode == "rediscover" --> rediscover boxes with new etcd discovery token.

    - name: Fail if boxnumber is not defined
      fail: msg="This role requires 'boxnumber' as a variable"
      when: boxnumber is not defined

    - name: Fail if libvirt_subnet is not defined
      fail: msg="This role requires 'libvirt_subnet' as a variable"
      when: libvirt_subnet is not defined

    - name: Fail if coreos_discovery is not defined
      fail: msg="This role requires 'coreos_discovery' as a variable"
      when: coreos_discovery is not defined

    - { include: libvirt_spinup.yml, when: mode == 'create' }
    - { include: libvirt_reloaduserdata.yml, when: mode == 'rediscover' }
    - { include: libvirt_destroy.yml, when: mode == 'destroy' }