---
# Install keepalived on specific hosts
# Generate binaries via this method: 
# https://github.com/aledbf/coreos-keepalived

- name: Install keepalived on coreos hosts
  hosts: 
    - keepalive_leader
    - keepalive_follower
  vars_files:
    - ["vars/private.yml", "vars/coreos.yml"]
  vars:
    floating_ip: "192.168.122.199"
    keepalived_password: "as877dvqf7s9d87DDnnZaZLMnB"
    # additional vars...
  sudo: true

  roles:
    - { role: keepalived-coreos }
