---
# Update fleet units on a coreos cluster.

- name: Update fleet unit files in cluster
  hosts: coreos
  sudo: true
  tasks:

    - name: Copy unit files
      copy: src=units/ dest=/home/core/units

- name: Sync asterisk configs
  hosts: asterisk
  vars_files:
    - vars/coreos.yml
  # vars:
  #   outbound_proxy: 192.168.122.200
  sudo: true
  tasks:

    - name: Ensure /etc/asterisk exists
      file: path=/etc/asterisk state=directory

    - name: Template sip.conf
      template: src=config/asterisk/sip.conf dest=/etc/asterisk/sip.conf

    - name: Copy dialplan
      copy: src=config/asterisk/extensions.conf dest=/etc/asterisk/extensions.conf

- name: Sync kamailio configs
  hosts: kamailio
  vars_files:
    - vars/coreos.yml
  sudo: true
  tasks:

    - name: Ensure /etc/kamailio exists
      file: path=/etc/kamailio state=directory

    - name: Copy kamailio config
      copy: src=config/kamailio.cfg dest=/etc/kamailio/kamailio.cfg

    - name: Ensure /etc/keepalived exists
      file: path=/etc/keepalived state=directory

    - name: Template keepalived.conf
      template: src=config/keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf

- name: Update fleet units in cluster
  hosts: leader
  vars:
    units:
      - dispatcher@.service
      - kamailio@.service
      - asterisk@.service
      - announcer@.service
      - keepalived@.service
    instances:
      - { unit: kamailio,   instance: 1 }
      - { unit: kamailio,   instance: 2 }
      - { unit: keepalived, instance: 1 }
      - { unit: keepalived, instance: 2 }
      - { unit: dispatcher, instance: 1 }
      - { unit: dispatcher, instance: 2 }
      - { unit: asterisk,   instance: 1 }
      - { unit: asterisk,   instance: 2 }
      - { unit: announcer,  instance: 1 }
      - { unit: announcer,  instance: 2 }
  sudo: true
  tasks:

    - name: Destroy existing base unit files
      command: "fleetctl destroy {{ item }}"
      with_items: units
      args:
        chdir: /home/core/units

    - name: Destroy instances
      command: "fleetctl destroy {{ item.unit }}@{{ item.instance }}"
      with_items: instances

    - name: Load new unit files
      command: "fleetctl submit {{ item }}"
      with_items: units
      args:
        chdir: /home/core/units

    - name: Spin up instances
      command: "fleetctl start {{ item.unit }}@{{ item.instance }}"
      with_items: instances